#!/bin/sh
emoji=$(cat ~/.local/bin/resources/emojilist | rofi -dmenu -i | sed 's/:.*//')
[ -z "$emoji" ] && exit 0
echo "$emoji" | tr -d '\n' | xclip -selection clipboard && notify-send "$(xclip -o -selection clipboard) copied to clipboard."
